spring.application.name=hmh
# Thymeleaf? ?? ?? ??
spring.thymeleaf.cache=false

# ?? HTML? ?? ???(static ??)? ?? ?? ??
spring.web.resources.cache.period=0

# Aiven PostgreSQL DB ?? ?? (sslmode=require ??)
spring.datasource.url=jdbc:postgresql://hmh-db-hmh.a.aivencloud.com:11926/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis ??
# 1. ??? ??? XML ?? ??
mybatis.mapper-locations=classpath:mapper/**/*.xml

# 2. XML?? 'com.hmh.domain.Member'?? ?? ? ?? ?? 'Member'?? ? ? ?? ??
mybatis.type-aliases-package=com.hmh.domain

# 3. [???] DB? ???? ???(user_id)? ??? ?? ???(userId)? ?? ??!
mybatis.configuration.map-underscore-to-camel-case=true