spring.application.name=hmh
# Thymeleaf? ?? ?? ??
spring.thymeleaf.cache=false

# ?? HTML? ?? ???(static ??)? ?? ?? ??
spring.web.resources.cache.period=0

# Aiven PostgreSQL DB ?? ?? (sslmode=require ??)
spring.datasource.url=jdbc:postgresql://hmh-db-hmh.a.aivencloud.com:11926/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis ??
# 1. ??? ??? XML ?? ??
mybatis.mapper-locations=classpath:mapper/**/*.xml

# 2. XML?? 'com.hmh.domain.Member'?? ?? ? ?? ?? 'Member'?? ? ? ?? ??
mybatis.type-aliases-package=com.hmh.domain, com.hmh.dto

# 3. [???] DB? ???? ???(user_id)? ??? ?? ???(userId)? ?? ??!
mybatis.configuration.map-underscore-to-camel-case=true

# 1. P6Spy 로깅 명시적 활성화
decorator.datasource.p6spy.enable-logging=true

# 2. 쿼리를 보기 좋게 여러 줄로 출력 (권장)
decorator.datasource.p6spy.multiline=true

# 3. P6Spy의 로그 레벨 설정 (스프링 부트 로거가 이걸 콘솔에 뿌려주도록 INFO 설정)
logging.level.p6spy=INFO